import Link from "next/link";
import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";

export const metadata = {
  title: "Terms of Service — RAMS Generator",
  description: "Terms and conditions for using RAMS Generator.",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#0a1628] flex flex-col">
      <Navbar />
      <main className="flex-1 max-w-3xl mx-auto px-6 py-16 w-full">
        <p className="text-blue-400 text-xs font-bold uppercase tracking-widest mb-3">Legal</p>
        <h1 className="text-4xl font-black text-white mb-2">Terms of Service</h1>
        <p className="text-slate-500 text-sm mb-10">Last updated: July 2026</p>

        <div className="space-y-8 text-slate-300 text-sm leading-relaxed">
          <section className="bg-amber-500/10 border border-amber-500/30 rounded-xl p-4">
            <p className="text-amber-300 font-semibold text-sm">
              Important: RAMS Generator is an assistive tool only. All generated documents must be reviewed and
              approved by a competent H&amp;S person before use on site. You are responsible for the accuracy and
              completeness of any RAMS document you issue.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-3">1. Service description</h2>
            <p>
              RAMS Generator provides an AI-assisted and template-based tool to help UK construction subcontractors
              draft Risk Assessment and Method Statement (RAMS) documents. The service is provided &quot;as is&quot; without
              warranty of any kind.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-3">2. Not a substitute for professional advice</h2>
            <p>
              The documents produced by RAMS Generator are a <strong className="text-white">starting point only</strong>.
              They are not a substitute for:
            </p>
            <ul className="list-disc pl-5 space-y-1 mt-2">
              <li>Site-specific risk assessment by a competent person</li>
              <li>Professional health and safety advice from a qualified practitioner</li>
              <li>Consultation with the Principal Contractor or CDM Coordinator</li>
              <li>Compliance with site-specific rules, Construction Phase Plan requirements, or permit systems</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-3">3. User responsibilities</h2>
            <p>By using RAMS Generator you agree that:</p>
            <ul className="list-disc pl-5 space-y-1 mt-2">
              <li>You are responsible for reviewing all generated content before issuing it to any party</li>
              <li>All generated RAMS documents must be reviewed by a competent person before use on site</li>
              <li>You will not use generated documents without site-specific verification of their accuracy</li>
              <li>You will not misrepresent AI-generated content as independently authored documentation</li>
              <li>You accept sole responsibility for any consequences arising from use of generated documents on site</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-3">4. Legislation references</h2>
            <p>
              RAMS Generator references UK health and safety legislation as it stood at the time of development. You
              are responsible for verifying that all legislation references in generated documents are current and
              applicable to your specific works. Legislation is regularly amended — always check against the official
              source at{" "}
              <a
                href="https://www.legislation.gov.uk"
                target="_blank"
                rel="noopener noreferrer"
                className="text-blue-400 hover:text-blue-300 underline"
              >
                legislation.gov.uk
              </a>
              .
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-3">5. Limitation of liability</h2>
            <p>
              To the fullest extent permitted by law, we accept no liability for any loss, injury, or damage arising
              from use of documents generated by this service. This includes but is not limited to incidents on site
              arising from incomplete, inaccurate, or inappropriately applied RAMS documents.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-3">6. Changes to these terms</h2>
            <p>
              We reserve the right to update these terms at any time. Continued use of the service constitutes
              acceptance of the updated terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-3">7. Contact</h2>
            <p>
              For any queries relating to these terms, contact{" "}
              <a href="mailto:ledjo.lutaj@gmail.com" className="text-blue-400 hover:text-blue-300 underline">
                ledjo.lutaj@gmail.com
              </a>
              .
            </p>
          </section>
        </div>

        <div className="mt-12 pt-6 border-t border-slate-800">
          <Link href="/" className="text-sm text-slate-500 hover:text-slate-300 transition-colors">
            ← Back to home
          </Link>
        </div>
      </main>
      <Footer />
    </div>
  );
}
